# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        ca-certificates
        cpio
        curl
        dosfstools
        e2fsprogs
        keyutils
        kmod
        mtools
        opensc
        openssl
        systemd
        tar
        xfsprogs
        zstd
